# Adding missing packages to the renv lock file
# https://rstudio.github.io/renv/reference/dependencies.html
library(tidyverse)
library(sf)
library(rticles)
library(remotes)
# remotes::install_github("zehuiyin/GroceryStoreHamiltonData")
library(GroceryStoreHamiltonData)
library(pscl)
library(texreg)
library(mapview)
library(tidytransit)
library(tmap)
library(tmaptools)
library(OpenStreetMap)
library(marginaleffects)
library(patchwork)